//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alluminati.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlluminatiEntities : DbContext
    {
        public AlluminatiEntities()
            : base("name=AlluminatiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblLogin> tblLogin { get; set; }
        public DbSet<tblModelos> tblModelos { get; set; }
        public DbSet<tblUsuarios> tblUsuarios { get; set; }
    }
}
