//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alluminati.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int IdLogin { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
