//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alluminati.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarios
    {
        public tblUsuarios()
        {
            this.tblLogin = new HashSet<tblLogin>();
        }
    
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string CorreoElectronico { get; set; }
        public string Direccion { get; set; }
        public int Telefono { get; set; }
        public string Privilegios { get; set; }
        public int Estatus { get; set; }
    
        public virtual ICollection<tblLogin> tblLogin { get; set; }
    }
}
